//! Handshake frames: `hello`, `auth_response`, `approve`, `deny`.
//!
//! The hello/auth_response pair binds both sides to two independently
//! drawn contributions and to the exact channel, and proves possession
//! of the private key matching each peer's claimed Device ID. Approve/
//! deny is the user-facing trust gate that fires once mutual auth is
//! verified.
//!
//! These structs are the wire envelope only. The bytes actually signed
//! are the Arc 04 endpoint-auth transcript built by
//! [`crate::endpoint_auth`]; the legacy
//! [`crate::signing::handshake_payload`] helper is retained but is no
//! longer produced or accepted on the live path.

use serde::{Deserialize, Serialize};

use super::rpc::CapabilityAdvert;
use crate::network_state::Transition;

/// Sent immediately on channel open by both ends. Carries the
/// sender's claimed Device ID, this endpoint's per-attempt
/// contribution, and an optional capabilities blob. Both sides' hellos
/// are required: each contribution is bound into the signed transcript.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HelloMessage {
    /// Wire-protocol version. v1 senders MAY omit features the
    /// receiver doesn't advertise; v1 receivers MUST silently drop
    /// unknown message kinds.
    pub protocol: u32,
    /// Bare-pubkey Device ID, base32-lowercase. Display suffix
    /// omitted on the wire — the receiver derives it themselves if
    /// they want to show the peer to the user.
    pub device_id: String,
    /// Self-reported label. Cosmetic; peers cannot rely on labels
    /// for identity.
    #[serde(default)]
    pub label: String,
    /// This endpoint's per-attempt contribution: a fresh 32-byte CSPRNG
    /// draw, base32-lowercase, accepted only in that exact canonical
    /// encoding. It is one of two contributions bound into the signed
    /// endpoint-auth transcript, and — because the certificate-fingerprint
    /// channel binding is not session-unique — this freshness is what
    /// separates one attempt from another.
    pub nonce: String,
    /// Short human-readable verification code (6 chars, `[a-z0-9]`)
    /// generated by the sender. Displayed prominently on both sides
    /// during a pending approval so the users can confirm by
    /// out-of-band channel ("hey I'm sending a request, my code is
    /// X") that the request they see is really from the person they
    /// think it is. Not load-bearing — the ed25519 signatures
    /// authenticate identity; this is just the UX anchor.
    pub verification_code: String,
    /// Capabilities the sender advertises. Optional — omitted by
    /// older peers; receivers treat absence as
    /// [`CapabilityAdvert::default`].
    #[serde(default)]
    pub capabilities: Option<CapabilityAdvert>,
    /// Maximum concurrent connections this peer is willing to
    /// maintain. Feeds the topology selector — a peer that says
    /// "I can hold 8" absorbs more of the load when nearby ones
    /// are at the floor. Omitted by older peers; the engine
    /// defaults to 6 when missing.
    #[serde(default)]
    pub max_connections: Option<u32>,
    /// Capability-negotiation list — see [`super::features`]. Older
    /// peers omit; receivers treat absence as an empty list.
    #[serde(default)]
    pub features: Vec<String>,
    /// Sender's app version. Cosmetic only; surfaced in the peer
    /// detail UI so users can see when a peer is on an older /
    /// newer release than them.
    #[serde(default)]
    pub app_version: Option<String>,
}

/// Response to [`HelloMessage`] proving the sender controls the
/// private key matching `HelloMessage::device_id`. The receiver
/// verifies the signature against the peer's pubkey; on failure
/// the connection is torn down without prompting the user.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthResponseMessage {
    /// Base32-lowercase signature over the Arc 04 endpoint-auth
    /// transcript, under `ENDPOINT_AUTH_DOMAIN_TAG`.
    ///
    /// This is a hard cutover, not a negotiation: a signature over the
    /// legacy `SIGN_DOMAIN_TAG` payload is rejected by domain separation
    /// rather than accepted as a fallback, so there is nothing for an
    /// attacker to select down to. An older peer fails authentication.
    pub signature: String,
}

/// Sent by the local side once the peer is cleared for app traffic:
/// either auto-approved from the roster, or the user clicked
/// "approve" in the network browser. Both sides must observe each
/// other's approve before the connection transitions to ACTIVE.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApproveMessage {}

/// The `reason` a [`DenyMessage`] carries when the denial is "this
/// network's signed governance EVICTED you." Such a deny also attaches
/// the signed logs as proof, so the denied device can verify its own
/// eviction and stand down instead of redialing forever.
pub const DENY_REASON_EVICTED: &str = "evicted";

/// Sent when the local side rejects the peer. The peer should not
/// reconnect until the user approves again (the engine treats this
/// as a hint, not a hard ban — repeated reconnect attempts after a
/// deny just get re-denied, but the user can reverse the decision
/// from the network browser).
///
/// One denial is different: `reason == `[`DENY_REASON_EVICTED`] means
/// the network's **signed state** removed the peer, and the deny
/// carries that state as proof (`transitions` + `member_log`). The
/// denied device never trusts the denier — it routes the logs through
/// the same strict-extension verification every log adoption takes
/// (the owner's signatures are the authority), and only a verdict its
/// OWN verified state agrees with makes it stand down. A device
/// evicted while offline finally has a way to *learn* it: today it
/// redialed forever and, on auto-approve networks, kept resurrecting
/// itself into rosters ("offline and lost devices keep showing up").
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DenyMessage {
    #[serde(default)]
    pub reason: Option<String>,
    /// The network's signed governance log (proof for an eviction
    /// denial). Empty on ordinary denies; absent from older peers'
    /// frames via `#[serde(default)]`, which also means an older
    /// receiver simply ignores the extra fields — it is denied
    /// exactly as before, just without the ability to self-verify.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub transitions: Vec<Transition>,
    /// The signed member-tier log (the half that actually carries a
    /// member's `Evict`). Same compat story as `transitions`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub member_log: Vec<Transition>,
}
