//! Handshake frames: `hello`, `auth_response`, `approve`, `deny`.
//!
//! The hello/auth_response pair binds both sides to two independently
//! drawn contributions and to the exact channel, and proves possession
//! of the private key matching each peer's claimed Device ID. Approve/
//! deny is the user-facing trust gate that fires once mutual auth is
//! verified.
//!
//! These structs are the wire envelope only. The bytes actually signed are the
//! endpoint-auth transcript built by [`crate::endpoint_auth`]; there is no
//! alternate handshake-signature payload in this hard-alpha profile.

use serde::{Deserialize, Serialize};

use crate::network_state::Transition;

pub(crate) fn verification_code_has_protocol_shape(code: &str) -> bool {
    code.len() == 6
        && code
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit())
}

/// Sent immediately on channel open by both ends. Carries the
/// sender's claimed Device ID and this endpoint's per-attempt
/// contribution. Both sides' hellos are required: each contribution is
/// bound into the signed transcript.
///
/// **This frame is admitted before a session exists**, so it carries only what
/// endpoint authentication and the approval gate need in order to run. It
/// carries no application capability metadata: that is exchanged after
/// promotion, through `CapabilitiesUpdate` under a live `SessionCapability`,
/// which is the only path where a peer's advertisement can reach application
/// state at all. A capability blob here would be attacker-controlled input
/// mutating and announcing application-level metadata before the
/// application-payload boundary — and an "absent means default" rule would
/// additionally manufacture an advertisement no peer ever sent.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HelloMessage {
    /// Wire-protocol version. The frame set is closed: a receiver refuses any
    /// kind this build does not implement, which fails to deserialize and
    /// reaches no handler. This alpha has no optional-frame negotiation.
    pub protocol: u32,
    /// Bare-pubkey Device ID, base32-lowercase. Display suffix
    /// omitted on the wire — the receiver derives it themselves if
    /// they want to show the peer to the user.
    pub device_id: String,
    /// Self-reported label. Cosmetic; peers cannot rely on labels
    /// for identity.
    #[serde(default)]
    pub label: String,
    /// This endpoint's per-attempt contribution: a fresh 32-byte CSPRNG
    /// draw, base32-lowercase, accepted only in that exact canonical
    /// encoding. It is one of two contributions bound into the signed
    /// endpoint-auth transcript, and — because the certificate-fingerprint
    /// channel binding is not session-unique — this freshness is what
    /// separates one attempt from another.
    pub nonce: String,
    /// Short human-readable verification code (6 chars, `[a-z0-9]`)
    /// generated by the sender. Displayed prominently on both sides
    /// during a pending approval so the users can confirm by
    /// out-of-band channel ("hey I'm sending a request, my code is
    /// X") that the request they see is really from the person they
    /// think it is. Not load-bearing — the ed25519 signatures
    /// authenticate identity; this is just the UX anchor.
    pub verification_code: String,
    /// Protocol-feature list — see [`super::features`]. Read before a session
    /// exists because that is what it is for: `endpoint_auth_v1` is how a peer
    /// states it speaks the one closed authentication profile, and its absence
    /// is a fail-closed refusal. It advertises no application capability and
    /// names no application semantics.
    ///
    /// `#[serde(default)]` here is not an older-peer accommodation: an empty
    /// list is the honest reading of a peer that advertised nothing, and it
    /// refuses rather than enabling anything.
    #[serde(default)]
    pub features: Vec<String>,
}

/// Response to [`HelloMessage`] proving the sender controls the
/// private key matching `HelloMessage::device_id`. The receiver
/// verifies the signature against the peer's pubkey; on failure
/// the connection is torn down without prompting the user.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthResponseMessage {
    /// Base32-lowercase signature over the Arc 04 endpoint-auth
    /// transcript, under `ENDPOINT_AUTH_DOMAIN_TAG`.
    ///
    /// This is a hard cutover, not a negotiation: a signature over any other
    /// payload is rejected by domain separation rather than accepted as a
    /// fallback. Anything outside the current profile fails authentication.
    pub signature: String,
}

/// Sent by the local side once the peer is cleared for app traffic:
/// either auto-approved from the roster, or the user clicked
/// "approve" in the network browser. Both sides must observe each
/// other's approve before the connection transitions to ACTIVE.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApproveMessage {}

/// The `reason` a [`DenyMessage`] carries when the denial is "this
/// network's signed governance EVICTED you." Such a deny also attaches
/// the signed logs as proof, so the denied device can verify its own
/// eviction and stand down instead of redialing forever.
pub const DENY_REASON_EVICTED: &str = "evicted";

/// Sent when the local side rejects the peer. The peer should not
/// reconnect until the user approves again (the engine treats this
/// as a hint, not a hard ban — repeated reconnect attempts after a
/// deny just get re-denied, but the user can reverse the decision
/// from the network browser).
///
/// One denial is different: `reason == `[`DENY_REASON_EVICTED`] means
/// the network's **signed state** removed the peer, and the deny
/// carries that state as proof (`transitions` + `member_log`). The
/// denied device never trusts the denier — it routes the logs through
/// the same strict-extension verification every log adoption takes
/// (the owner's signatures are the authority), and only a verdict its
/// OWN verified state agrees with makes it stand down. A device
/// evicted while offline finally has a way to *learn* it: today it
/// redialed forever and, on auto-approve networks, kept resurrecting
/// itself into rosters ("offline and lost devices keep showing up").
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DenyMessage {
    #[serde(default)]
    pub reason: Option<String>,
    /// The network's signed governance log (proof for an eviction
    /// denial). Empty on ordinary denies, where the current wire shape omits
    /// the field.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub transitions: Vec<Transition>,
    /// The signed member-tier log (the half that actually carries a
    /// member's `Evict`). Empty on an ordinary denial.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub member_log: Vec<Transition>,
}

#[cfg(test)]
mod verification_code_tests {
    use super::verification_code_has_protocol_shape;

    #[test]
    fn verification_code_is_exactly_six_lowercase_ascii_alphanumerics() {
        assert!(verification_code_has_protocol_shape("abc123"));
        for malformed in ["abc12", "abc1234", "ABC123", "abc-12", "\u{e5}bc123"] {
            assert!(
                !verification_code_has_protocol_shape(malformed),
                "{malformed:?}"
            );
        }
    }
}
